/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package museupoo.GUI;

import br.com.fatec.vo.EventoVO;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import museupoo.Content;
import museupoo.UTIL.Util;

/**
 *
 * @author Victor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Content content;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Content content) 
    {
        initComponents();
        this.content = content;
        iniciaRelogio();
      
        buscaEventoData(Calendar.getInstance());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bttOntem = new javax.swing.JButton();
        bttAmanha = new javax.swing.JButton();
        bttHoje = new javax.swing.JButton();
        pnlEvento = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        lblDataInicial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTexto2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtInteira = new javax.swing.JTextField();
        txtMeia = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        bttMinusInteira = new javax.swing.JButton();
        bttPlusInteira = new javax.swing.JButton();
        bttPlusMeia = new javax.swing.JButton();
        bttMinusMeia = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        bttEditarEvento = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblDataHora = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(" Controle de Entrada "));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Selecione a data:");

        bttOntem.setText("Ontem");
        bttOntem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttOntemActionPerformed(evt);
            }
        });

        bttAmanha.setText("Amanha");
        bttAmanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAmanhaActionPerformed(evt);
            }
        });

        bttHoje.setText("Hoje");
        bttHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHojeActionPerformed(evt);
            }
        });

        pnlEvento.setBorder(javax.swing.BorderFactory.createTitledBorder(" Evento "));
        pnlEvento.setToolTipText("");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescricao.setText("Descrição:");
        lblDescricao.setEnabled(pnlEvento.isEnabled());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Texto 1:");
        jLabel4.setEnabled(pnlEvento.isEnabled());

        lblTexto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTexto2.setText("Texto 2:");
        lblTexto2.setEnabled(pnlEvento.isEnabled());

        lblDataFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataFinal.setText("Data Final:");
        lblDataFinal.setEnabled(pnlEvento.isEnabled());

        lblDataInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataInicial.setText("Data Inicial:");
        lblDataInicial.setEnabled(pnlEvento.isEnabled());

        txtTexto1.setColumns(20);
        txtTexto1.setRows(5);
        txtTexto1.setEnabled(pnlEvento.isEnabled());
        jScrollPane1.setViewportView(txtTexto1);

        txtTexto2.setColumns(20);
        txtTexto2.setRows(5);
        txtTexto2.setEnabled(pnlEvento.isEnabled());
        jScrollPane2.setViewportView(txtTexto2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(" Entradas "));
        jPanel6.setEnabled(pnlEvento.isEnabled());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Inteiras:");
        jLabel8.setEnabled(pnlEvento.isEnabled());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Meia:");
        jLabel9.setEnabled(pnlEvento.isEnabled());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Total:");
        jLabel10.setEnabled(pnlEvento.isEnabled());

        txtInteira.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtInteira.setEnabled(pnlEvento.isEnabled());

        txtMeia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtMeia.setEnabled(pnlEvento.isEnabled());

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTotal.setEnabled(pnlEvento.isEnabled());

        bttMinusInteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/minus.png"))); // NOI18N
        bttMinusInteira.setEnabled(pnlEvento.isEnabled());

        bttPlusInteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/plus.png"))); // NOI18N
        bttPlusInteira.setEnabled(pnlEvento.isEnabled());

        bttPlusMeia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/plus.png"))); // NOI18N
        bttPlusMeia.setEnabled(pnlEvento.isEnabled());

        bttMinusMeia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/minus.png"))); // NOI18N
        bttMinusMeia.setEnabled(pnlEvento.isEnabled());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(txtInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttPlusInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttMinusInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttPlusMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttMinusMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(bttPlusMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bttMinusMeia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(bttPlusInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(bttMinusInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtInteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(txtMeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/bttIniciar.png"))); // NOI18N
        jToggleButton1.setEnabled(pnlEvento.isEnabled());

        bttEditarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/museupoo/GUI/Imagem/bttEditarEvento.png"))); // NOI18N
        bttEditarEvento.setEnabled(pnlEvento.isEnabled());

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnlEventoLayout = new javax.swing.GroupLayout(pnlEvento);
        pnlEvento.setLayout(pnlEventoLayout);
        pnlEventoLayout.setHorizontalGroup(
            pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEventoLayout.createSequentialGroup()
                        .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEventoLayout.createSequentialGroup()
                                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlEventoLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEventoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTexto2))
                                    .addGroup(pnlEventoLayout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bttEditarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlEventoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventoLayout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addGap(181, 181, 181))
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlEventoLayout.setVerticalGroup(
            pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEventoLayout.createSequentialGroup()
                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblDataInicial)
                    .addComponent(lblDataFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttEditarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEventoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDataHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDataHora.setText("26/05/2014    10:59");

        lblAviso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAviso.setText("Sem eventos cadastrados...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(255, 255, 255)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bttOntem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttHoje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttAmanha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataHora)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDataHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAviso)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bttAmanha)
                                .addComponent(bttHoje))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bttOntem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(pnlEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jMenu1.setText("Iniciar");

        jMenuItem6.setText("Configurar Banco");
        jMenu1.add(jMenuItem6);

        jMenuItem5.setText("Sair");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Manutenção");

        jMenuItem2.setText("Funcionarios");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Evento");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Obra");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttOntemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttOntemActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        c.add(Calendar.DATE, -1);
        buscaEventoData(c);
    }//GEN-LAST:event_bttOntemActionPerformed

    private void bttHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHojeActionPerformed
        // TODO add your handling code here:
        buscaEventoData(Calendar.getInstance());
    }//GEN-LAST:event_bttHojeActionPerformed

    private void bttAmanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAmanhaActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        c.add(Calendar.DATE, 1);
        buscaEventoData(c);
    }//GEN-LAST:event_bttAmanhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAmanha;
    private javax.swing.JButton bttEditarEvento;
    private javax.swing.JButton bttHoje;
    private javax.swing.JButton bttMinusInteira;
    private javax.swing.JButton bttMinusMeia;
    private javax.swing.JButton bttOntem;
    private javax.swing.JButton bttPlusInteira;
    private javax.swing.JButton bttPlusMeia;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JPanel pnlEvento;
    private javax.swing.JTextField txtInteira;
    private javax.swing.JTextField txtMeia;
    private javax.swing.JTextArea txtTexto1;
    private javax.swing.JTextArea txtTexto2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void iniciaRelogio() 
    {
       
    ActionListener action = new ActionListener() {  
            public void actionPerformed(@SuppressWarnings("unused") java.awt.event.ActionEvent e) 
            {  
                Date data = new Date();
                lblDataHora.setText(Util.DateTimeString(data));
            }  
        };  
      Date data = new Date();
      lblDataHora.setText(Util.DateTimeString(data));
        Timer t = new Timer(20000, action);  
        t.start(); 
        
    }

    private void buscaEventoData(Calendar date) {
        
        try 
        {
            EventoVO evAtual = content.eventoDAO.buscarData(Util.DateStringSQL(date));
            if(evAtual != null)
            {
                lblAviso.setText("");
                pnlEvento.setEnabled(true);
                content.setEventoAtual(evAtual);
                lblDescricao.setText("Descrição:"+ evAtual.getDescricao());
                lblDataInicial.setText("Data Inicial:" + Util.DateTimeString(evAtual.getDataInicio()));
                lblDataFinal.setText("Data Final:" + Util.DateTimeString(evAtual.getDataFinal()));
                txtTexto1.setText(evAtual.getTexto1());
                txtTexto2.setText(evAtual.getTexto2());
                
            }
            else
            {
                //sem evento para data
                lblAviso.setText("Sem evento cadastrado...");
                pnlEvento.setEnabled(false);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
}
